jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
        shell: cmd

      - name: Clean previous builds
        run: |
          if exist build rmdir /s /q build
          if exist dist rmdir /s /q dist
          if exist rolo_rec.egg-info rmdir /s /q rolo_rec.egg-info
        shell: cmd

      - name: Download face.pt
        run: |
          mkdir myfacerec\models
          curl -L -o myfacerec/models/face.pt https://raw.githubusercontent.com/wuhplaptop/facerec/main/myfacerec/models/face.pt
        shell: bash

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel
        shell: cmd

      - name: Verify dist contents
        run: |
          echo "Checking dist directory contents:"
          dir dist
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-python-package
          path: dist/**/*

      # ------------------------
      # Test step: updated
      # ------------------------
      - name: Debug: Show test files
        run: |
          echo "Current directory is %CD%"
          dir
          echo "Now listing contents of 'tests' folder if present..."
          dir tests
          echo "Pytest --collect-only to see discovered tests:"
          python -m pytest tests --collect-only --disable-warnings -v
        shell: cmd

      - name: Run tests
        run: |
          REM Install the built package
          for %%f in (dist\*.whl) do pip install %%f || exit 1

          REM Install testing dependencies
  
