name: publish-pypi

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      #    This includes build tools (build, twine), test runner (pytest), and any library dev deps
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build twine pytest flake8  # adjust if you use black or mypy, etc.
          pip install -e .

      # 4. (Optional) Lint your code
      - name: Lint
        run: |
          flake8 .

      # 5. Run tests
      - name: Run tests
        run: |
          pytest

      # 6. Build the package (sdist + wheel)
      - name: Build package
        run: |
          python -m build

      # 7. Publish to PyPI if pushing a tag
      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
